# Generated by Django 5.0.3 on 2026-01-03 17:53

from django.db import migrations, models


def convert_hilfsmuskeln_to_json(apps, schema_editor):
    """Konvertiere alte CharField-Daten zu JSON-Liste"""
    Uebung = apps.get_model("core", "Uebung")
    for uebung in Uebung.objects.all():
        if uebung.hilfsmuskeln:
            # Wenn es ein String ist, konvertiere zu leerer Liste
            # (Alte Daten können später im Admin manuell gepflegt werden)
            if isinstance(uebung.hilfsmuskeln, str):
                uebung.hilfsmuskeln = []
                uebung.save()
        else:
            uebung.hilfsmuskeln = []
            uebung.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_plan_uebung_bewegungstyp_alter_uebung_gewichts_typ_and_more"),
    ]

    operations = [
        # Erst die Daten konvertieren
        migrations.RunPython(convert_hilfsmuskeln_to_json, migrations.RunPython.noop),
        # Dann das Feld ändern
        migrations.AlterField(
            model_name="uebung",
            name="hilfsmuskeln",
            field=models.JSONField(blank=True, default=list, verbose_name="Hilfsmuskelgruppen"),
        ),
    ]
