# Generated by Django 5.0.3 on 2026-01-03 21:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_trainingseinheit_plan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="uebung",
            name="favoriten",
            field=models.ManyToManyField(
                blank=True, related_name="favoriten_uebungen", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
