# Generated by Django 5.0.3 on 2026-01-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_uebung_favoriten"),
    ]

    operations = [
        migrations.AddField(
            model_name="satz",
            name="notiz",
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name="Notiz"),
        ),
    ]
