# Generated by Django 5.0.3 on 2026-01-04 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_satz_notiz"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "foto",
                    models.ImageField(upload_to="progress_photos/%Y/%m/", verbose_name="Foto"),
                ),
                ("datum", models.DateField(auto_now_add=True, verbose_name="Aufnahmedatum")),
                (
                    "gewicht_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional: Gewicht zum Zeitpunkt des Fotos",
                        max_digits=5,
                        null=True,
                        verbose_name="Gewicht (kg)",
                    ),
                ),
                (
                    "notiz",
                    models.CharField(
                        blank=True,
                        help_text="z.B. 'Start', 'Nach 3 Monaten', 'Bulking Phase'",
                        max_length=200,
                        null=True,
                        verbose_name="Notiz",
                    ),
                ),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fortschrittsfoto",
                "verbose_name_plural": "Fortschrittsfotos",
                "ordering": ["-datum"],
                "indexes": [
                    models.Index(fields=["user", "-datum"], name="core_progre_user_id_ddef18_idx")
                ],
            },
        ),
    ]
