# Generated by Django 5.0.3 on 2026-01-09 20:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_satz_superset_gruppe"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("LANGHANTEL", "Langhantel"),
                            ("KURZHANTEL", "Kurzhanteln"),
                            ("KETTLEBELL", "Kettlebell"),
                            ("BANK", "Flachbank"),
                            ("SCHRAEGBANK", "Schrägbank"),
                            ("KLIMMZUG", "Klimmzugstange"),
                            ("DIP", "Dipstation / Barren"),
                            ("KABELZUG", "Kabelzug / Latzug"),
                            ("BEINPRESSE", "Beinpresse"),
                            ("LEG_CURL", "Leg Curl Maschine"),
                            ("LEG_EXT", "Leg Extension Maschine"),
                            ("SMITHMASCHINE", "Smith Maschine"),
                            ("HACKENSCHMIDT", "Hackenschmidt"),
                            ("RUDERMASCHINE", "Rudermaschine"),
                            ("WIDERSTANDSBAND", "Widerstandsbänder"),
                            ("SUSPENSION", "Suspension Trainer (TRX)"),
                            ("MEDIZINBALL", "Medizinball"),
                            ("BOXEN", "Plyo Box"),
                            ("MATTE", "Trainingsmatte"),
                            ("KOERPER", "Nur Körpergewicht"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Equipment",
                    ),
                ),
                ("beschreibung", models.TextField(blank=True, verbose_name="Beschreibung")),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="verfuegbares_equipment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment",
                "verbose_name_plural": "Equipment",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="uebung",
            name="equipment",
            field=models.ManyToManyField(
                blank=True,
                related_name="uebungen",
                to="core.equipment",
                verbose_name="Benötigtes Equipment",
            ),
        ),
    ]
