# Generated by Django 5.0.3 on 2026-01-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_equipment_uebung_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='planuebung',
            name='trainingstag',
            field=models.CharField(blank=True, max_length=100, verbose_name='Trainingstag/Session'),
        ),
    ]
