# Generated by Django 5.0.3 on 2026-01-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_trainingstag_to_planuebung'),
    ]

    operations = [
        migrations.AddField(
            model_name='planuebung',
            name='superset_gruppe',
            field=models.PositiveIntegerField(default=0, help_text='0 = keine Gruppe, 1-9 = Gruppennummer für Supersätze', verbose_name='Superset-Gruppe'),
        ),
    ]
