# Generated by Django 5.0.3 on 2026-01-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_add_superset_gruppe_to_planuebung"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Öffentlich"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="name",
            field=models.CharField(
                choices=[
                    ("LANGHANTEL", "Langhantel"),
                    ("KURZHANTEL", "Kurzhanteln"),
                    ("KETTLEBELL", "Kettlebell"),
                    ("BANK", "Flachbank"),
                    ("SCHRAEGBANK", "Schrägbank"),
                    ("KLIMMZUG", "Klimmzugstange"),
                    ("DIP", "Dipstation / Barren"),
                    ("KABELZUG", "Kabelzug / Latzug"),
                    ("BEINPRESSE", "Beinpresse"),
                    ("LEG_CURL", "Leg Curl Maschine"),
                    ("LEG_EXT", "Leg Extension Maschine"),
                    ("SMITHMASCHINE", "Smith Maschine"),
                    ("HACKENSCHMIDT", "Hackenschmidt"),
                    ("RUDERMASCHINE", "Rudermaschine"),
                    ("WIDERSTANDSBAND", "Widerstandsbänder"),
                    ("SUSPENSION", "Suspension Trainer (TRX)"),
                    ("MEDIZINBALL", "Medizinball"),
                    ("BOXEN", "Plyo Box"),
                    ("MATTE", "Trainingsmatte"),
                    ("KOERPER", "Nur Körpergewicht"),
                    ("ADDUKTOREN_MASCHINE", "Adduktoren Maschine"),
                    ("ABDUKTOREN_MASCHINE", "Abduktoren Maschine"),
                ],
                max_length=50,
                unique=True,
                verbose_name="Equipment",
            ),
        ),
        migrations.AlterField(
            model_name="uebung",
            name="muskelgruppe",
            field=models.CharField(
                choices=[
                    ("BRUST", "Brust (Pectoralis major)"),
                    ("SCHULTER_VORN", "Schulter - Vordere (Deltoideus pars clavicularis)"),
                    ("SCHULTER_SEIT", "Schulter - Seitliche (Deltoideus pars acromialis)"),
                    ("SCHULTER_HINT", "Schulter - Hintere (Deltoideus pars spinalis)"),
                    ("TRIZEPS", "Trizeps (Triceps brachii)"),
                    ("RUECKEN_LAT", "Rücken - Breiter Muskel (Latissimus dorsi)"),
                    ("RUECKEN_TRAPEZ", "Rücken - Nacken/Trapez (Trapezius)"),
                    ("RUECKEN_UNTEN", "Unterer Rücken (Erector spinae)"),
                    ("BIZEPS", "Bizeps (Biceps brachii)"),
                    ("UNTERARME", "Unterarme (Brachioradialis/Flexoren)"),
                    ("RUECKEN_OBERER", "Oberer Rücken (Rhomboiden, mittlerer Trapez)"),
                    ("BEINE_QUAD", "Oberschenkel Vorn (Quadrizeps)"),
                    ("BEINE_HAM", "Oberschenkel Hinten (Hamstrings/Ischiocrurale)"),
                    ("PO", "Gesäß (Gluteus maximus/medius)"),
                    ("WADEN", "Waden (Gastrocnemius/Soleus)"),
                    ("ADDUKTOREN", "Oberschenkel Innen (Adduktoren)"),
                    ("ABDUKTOREN", "Oberschenkel Außen (Abduktoren)"),
                    ("HUEFTBEUGER", "Hüftbeuger (Iliopsoas)"),
                    ("BAUCH", "Bauch (Abdominals)"),
                    ("GANZKOERPER", "Ganzkörper / Cardio"),
                ],
                max_length=50,
                verbose_name="Hauptmuskel",
            ),
        ),
    ]
