# Generated by Django 5.0.3 on 2026-01-25 18:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_plan_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Einladungscode')),
                ('max_uses', models.IntegerField(default=1, help_text='Wie oft kann dieser Code verwendet werden?', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max. Verwendungen')),
                ('used_count', models.IntegerField(default=0, verbose_name='Bereits verwendet')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leer lassen für unbegrenzte Gültigkeit', null=True, verbose_name='Ablaufdatum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invite_codes', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Einladungscode',
                'verbose_name_plural': 'Einladungscodes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Mail')),
                ('reason', models.TextField(help_text='Warum möchtest du HomeGym nutzen?', verbose_name='Motivation')),
                ('experience', models.CharField(choices=[('beginner', 'Anfänger (< 1 Jahr Training)'), ('intermediate', 'Fortgeschritten (1-3 Jahre)'), ('advanced', 'Erfahren (> 3 Jahre)'), ('returning', 'Wiedereinstieg nach Pause')], max_length=20, verbose_name='Trainingserfahrung')),
                ('interests', models.JSONField(blank=True, default=list, help_text='Mehrfachauswahl möglich', verbose_name='Interessen')),
                ('github_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='GitHub Username (optional)')),
                ('status', models.CharField(choices=[('pending', 'Warteliste'), ('approved', 'Eingeladen'), ('registered', 'Registriert'), ('spam', 'Blockiert')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('invite_code', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entry', to='core.invitecode', verbose_name='Zugewiesener Code')),
            ],
            options={
                'verbose_name': 'Wartelisten-Eintrag',
                'verbose_name_plural': 'Warteliste',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='core_waitli_status_9a681c_idx'), models.Index(fields=['email'], name='core_waitli_email_4321a2_idx')],
            },
        ),
    ]
