# Generated by Django 5.0.3 on 2026-02-01 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_add_plan_gruppe_reihenfolge"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True,
                help_text="User, die diesen Plan sehen können (ohne öffentlich zu sein)",
                related_name="shared_plans",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Geteilt mit",
            ),
        ),
    ]
