# Generated by Django 5.0.3 on 2026-02-07 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_mlpredictionmodel'),
        ('core', '0050_fix_emoji_support'),
    ]

    operations = [
    ]
