# Generated by Django 5.0.3 on 2026-02-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_add_deload_params_to_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingseinheit",
            name="ist_deload",
            field=models.BooleanField(
                default=False,
                help_text="Deload-Trainings werden nicht in Statistiken (1RM, Volumen-Trends, Plateaus) eingerechnet",
                verbose_name="Deload-Training",
            ),
        ),
    ]
