# Generated by Django 5.0.3 on 2026-02-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_add_deload_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificDisclaimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1RM_STANDARDS', '1RM Standards'), ('FATIGUE_INDEX', 'Ermüdungsindex'), ('BODY_COMPOSITION', 'Körperkomposition'), ('TRAINING_VOLUME', 'Trainingsvolumen'), ('GENERAL', 'Allgemein')], max_length=50, unique=True, verbose_name='Kategorie')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('message', models.TextField(help_text='Markdown-formatierter Text. Nutze **fett**, *kursiv*, [Links](url)', verbose_name='Nachricht')),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warnung'), ('CRITICAL', 'Kritisch')], default='INFO', max_length=20, verbose_name='Schweregrad')),
                ('show_on_pages', models.JSONField(blank=True, default=list, help_text='Liste von URL-Patterns, z.B. ["uebungen/", "stats/"]', verbose_name='Seiten anzeigen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wissenschaftlicher Disclaimer',
                'verbose_name_plural': 'Wissenschaftliche Disclaimer',
                'ordering': ['category'],
            },
        ),
    ]
