# Generated by Django 5.1.15 on 2026-02-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_scientificdisclaimer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="name",
            field=models.CharField(
                choices=[
                    ("LANGHANTEL", "Langhantel"),
                    ("KURZHANTEL", "Kurzhanteln"),
                    ("KETTLEBELL", "Kettlebell"),
                    ("BANK", "Flachbank"),
                    ("SCHRAEGBANK", "Schrägbank"),
                    ("KLIMMZUG", "Klimmzugstange"),
                    ("DIP", "Dipstation / Barren"),
                    ("KABELZUG", "Kabelzug / Latzug"),
                    ("BEINPRESSE", "Beinpresse"),
                    ("LEG_CURL", "Leg Curl Maschine"),
                    ("LEG_EXT", "Leg Extension Maschine"),
                    ("SMITHMASCHINE", "Smith Maschine"),
                    ("HACKENSCHMIDT", "Hackenschmidt"),
                    ("RUDERMASCHINE", "Rudermaschine"),
                    ("WIDERSTANDSBAND", "Widerstandsbänder"),
                    ("SUSPENSION", "Suspension Trainer (TRX)"),
                    ("MEDIZINBALL", "Medizinball"),
                    ("BOXEN", "Plyo Box"),
                    ("MATTE", "Trainingsmatte"),
                    ("KOERPER", "Nur Körpergewicht"),
                    ("ADDUKTOREN_MASCHINE", "Adduktoren Maschine"),
                    ("ABDUKTOREN_MASCHINE", "Abduktoren Maschine"),
                    ("BRUSTPRESSE_MASCHINE", "Brustpresse Maschine"),
                ],
                max_length=50,
                unique=True,
                verbose_name="Equipment",
            ),
        ),
    ]
