# Generated by Django 5.1.15 on 2026-02-15 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_add_brustpresse_maschine_equipment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="plan",
            index=models.Index(fields=["user", "is_public"], name="plan_user_public_idx"),
        ),
        migrations.AddIndex(
            model_name="planuebung",
            index=models.Index(fields=["plan", "trainingstag"], name="planuebung_plan_tag_idx"),
        ),
        migrations.AddIndex(
            model_name="satz",
            index=models.Index(
                fields=["einheit", "ist_aufwaermsatz"], name="satz_einheit_warmup_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingseinheit",
            index=models.Index(fields=["user", "datum"], name="training_user_datum_idx"),
        ),
        migrations.AddIndex(
            model_name="trainingseinheit",
            index=models.Index(fields=["user", "ist_deload"], name="training_user_deload_idx"),
        ),
    ]
