# Generated by Django 5.1.15 on 2026-02-15 19:11

from django.conf import settings
from django.db import migrations, models


def mark_existing_as_done(apps, schema_editor):
    """Alle bestehenden Trainings gelten als abgeschlossen."""
    Trainingseinheit = apps.get_model("core", "Trainingseinheit")
    Trainingseinheit.objects.all().update(abgeschlossen=True)


def reverse_mark(apps, schema_editor):
    pass  # Kein sinnvolles Reverse nötig


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_phase_4_2_database_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingseinheit",
            name="abgeschlossen",
            field=models.BooleanField(
                default=False,
                help_text="Wird auf True gesetzt wenn der User das Training explizit abgeschlossen hat",
                verbose_name="Abgeschlossen",
            ),
        ),
        migrations.RunPython(mark_existing_as_done, reverse_mark),
        migrations.AddIndex(
            model_name="trainingseinheit",
            index=models.Index(fields=["user", "abgeschlossen"], name="training_user_done_idx"),
        ),
    ]
