# Generated by Django 5.1.15 on 2026-02-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_add_abgeschlossen_to_trainingseinheit"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("VOLUME", "Trainingsvolumen"),
                            ("INTENSITY", "Trainingsintensität / RPE"),
                            ("RECOVERY", "Regeneration & Deload"),
                            ("PERIODIZATION", "Periodisierung"),
                            ("ONE_RM", "1RM & Kraftstandards"),
                            ("BODY_COMP", "Körperkomposition"),
                            ("GENERAL", "Allgemein"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Kategorie",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Titel")),
                (
                    "authors",
                    models.CharField(
                        help_text='Format: "Nachname, V., & Nachname, V."',
                        max_length=400,
                        verbose_name="Autoren",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="Jahr")),
                (
                    "journal",
                    models.CharField(blank=True, max_length=200, verbose_name="Journal / Verlag"),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        help_text="Ohne https://doi.org/ Prefix, z.B. 10.1080/02640414.2016.1210197",
                        max_length=200,
                        verbose_name="DOI",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Direkter Link zur Quelle (optional, als Fallback wenn kein DOI)",
                        verbose_name="URL",
                    ),
                ),
                (
                    "key_findings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Liste von Strings, z.B. ["Höheres Volumen korreliert mit mehr Hypertrophie"]',
                        verbose_name="Key Findings",
                    ),
                ),
                (
                    "applies_to",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Steuert wo Tooltips erscheinen. Mögliche Werte: "fatigue_index", "1rm_standards", "rpe_quality", "plateau_analysis", "volume_metrics", "general"',
                        verbose_name="Anwendungsbereiche",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Wissenschaftliche Quelle",
                "verbose_name_plural": "Wissenschaftliche Quellen",
                "ordering": ["category", "year", "authors"],
                "indexes": [
                    models.Index(fields=["category", "is_active"], name="source_cat_active_idx")
                ],
            },
        ),
    ]
