# Generated by Django 5.1.15 on 2026-02-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_fix_wadenheben_gewichtstyp"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="groesse_cm",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Wird für BMI- und FFMI-Berechnung verwendet",
                null=True,
                verbose_name="Körpergröße (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="koerperwerte",
            name="groesse_cm",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Benötigt für BMI/FFMI – wird aus Profil übernommen",
                null=True,
                verbose_name="Größe (cm)",
            ),
        ),
    ]
