# Generated by Django 5.1.15 on 2026-02-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_add_groesse_to_userprofile_optional_koerperwerte"),
    ]

    operations = [
        migrations.AddField(
            model_name="koerperwerte",
            name="muskelmasse_prozent",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True, verbose_name="Muskeln (%)"
            ),
        ),
    ]
