# Generated by Django 5.1.15 on 2026-02-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_add_muskelmasse_prozent"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="ai_analysis_count_today",
            field=models.PositiveIntegerField(default=0, verbose_name="KI-Analyse-Calls heute"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ai_counter_reset_date",
            field=models.DateField(
                blank=True,
                help_text="Datum des letzten täglichen Resets (UTC)",
                null=True,
                verbose_name="Letzter Counter-Reset",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ai_guidance_count_today",
            field=models.PositiveIntegerField(
                default=0, verbose_name="KI-Live-Guidance-Calls heute"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ai_plan_count_today",
            field=models.PositiveIntegerField(
                default=0, verbose_name="KI-Plan-Generierungen heute"
            ),
        ),
    ]
