# Generated by Django 5.1.15 on 2026-02-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_add_ai_rate_limit_counters"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="trainings_pro_woche",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Wie viele Trainings pro Woche angestrebt werden (1-7)",
                verbose_name="Trainings-Ziel pro Woche",
            ),
        ),
    ]
