# Generated by Django 5.1.15 on 2026-02-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_add_ai_rate_limit_counters"),
    ]

    operations = [
        migrations.AddField(
            model_name="planuebung",
            name="notiz",
            field=models.TextField(
                blank=True,
                help_text="Technik-Hinweis oder Erinnerung die beim Training angezeigt wird",
                null=True,
                verbose_name="Übungshinweis",
            ),
        ),
        migrations.AlterField(
            model_name="satz",
            name="notiz",
            field=models.TextField(blank=True, null=True, verbose_name="Notiz"),
        ),
    ]
