# Generated by Django 5.1.15 on 2026-02-19 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_planuebung_notiz_satz_notiz_ohne_maxlength"),
        ("core", "0069_userprofile_trainings_pro_woche"),
    ]

    operations = []
