# Generated by Django 5.1.15 on 2026-02-22 01:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_merge_20260219_2114"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KIApiLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        choices=[
                            ("plan_generate", "Plan Generierung"),
                            ("plan_optimize", "Plan Optimierung"),
                            ("live_guidance", "Live Guidance"),
                            ("other", "Sonstiges"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Endpunkt",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="z.B. google/gemini-2.5-flash",
                        max_length=100,
                        verbose_name="Modell",
                    ),
                ),
                (
                    "tokens_input",
                    models.PositiveIntegerField(default=0, verbose_name="Input-Tokens"),
                ),
                (
                    "tokens_output",
                    models.PositiveIntegerField(default=0, verbose_name="Output-Tokens"),
                ),
                (
                    "cost_eur",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Kosten in Euro. Bei Ollama/lokal: 0.000000",
                        max_digits=8,
                        verbose_name="Kosten (€)",
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True,
                        help_text="False wenn LLM-Call fehlschlug oder Validierung scheiterte",
                        verbose_name="Erfolgreich",
                    ),
                ),
                (
                    "is_retry",
                    models.BooleanField(
                        default=False,
                        help_text="True wenn dieser Call ein Korrektur-Retry eines vorherigen Calls war",
                        verbose_name="Retry",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Leer bei Erfolg",
                        verbose_name="Fehlermeldung",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="Zeitpunkt"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ki_api_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "KI API Log",
                "verbose_name_plural": "KI API Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"], name="core_kiapil_user_id_fc1a2f_idx"
                    ),
                    models.Index(
                        fields=["endpoint", "created_at"], name="core_kiapil_endpoin_96d6a5_idx"
                    ),
                ],
            },
        ),
    ]
