# Generated by Django 5.1.15 on 2026-02-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_add_kiapi_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="KIApiCostSummary",
            fields=[],
            options={
                "verbose_name": "KI API Log",
                "verbose_name_plural": "KI API Logs & Kosten-Dashboard",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.kiapilog",),
        ),
        migrations.AlterField(
            model_name="plan",
            name="gruppe_name",
            field=models.CharField(
                blank=True,
                help_text="Name der Plangruppe (z.B. 'Push/Pull/Legs Split')",
                max_length=200,
                verbose_name="Gruppenname",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Name des Plans"),
        ),
    ]
