# Generated by Django 5.2.11 on 2026-02-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_plan_name_max_length_200"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ai_limit_plan_generation",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Wie viele Plan-Generierungen pro User/Tag (Standard: 3)",
                        verbose_name="KI-Limit: Plan-Generierung",
                    ),
                ),
                (
                    "ai_limit_live_guidance",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Wie viele Live-Guidance Calls pro User/Tag (Standard: 50)",
                        verbose_name="KI-Limit: Live-Guidance",
                    ),
                ),
                (
                    "ai_limit_analysis",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Wie viele Analyse-Calls pro User/Tag (Standard: 10)",
                        verbose_name="KI-Limit: Analysen",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Zuletzt geändert"),
                ),
            ],
            options={
                "verbose_name": "Site-Einstellungen",
                "verbose_name_plural": "Site-Einstellungen",
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="custom_ai_limit_analysis",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Falls gesetzt: überschreibt das globale Limit (leer = Standard verwenden)",
                null=True,
                verbose_name="Custom KI-Limit: Analysen",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="custom_ai_limit_guidance",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Falls gesetzt: überschreibt das globale Limit (leer = Standard verwenden)",
                null=True,
                verbose_name="Custom KI-Limit: Live-Guidance",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="custom_ai_limit_plan",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Falls gesetzt: überschreibt das globale Limit (leer = Standard verwenden)",
                null=True,
                verbose_name="Custom KI-Limit: Plan-Generierung",
            ),
        ),
    ]
