# Generated by Django 5.2.11 on 2026-02-23 22:27

from django.db import migrations


def create_initial_site_settings(apps, schema_editor):
    """Erstellt initial die SiteSettings mit Defaults aus settings.py."""
    SiteSettings = apps.get_model("core", "SiteSettings")

    # Nur erstellen falls noch nicht vorhanden
    if not SiteSettings.objects.exists():
        SiteSettings.objects.create(
            id=1,  # Singleton
            ai_limit_plan_generation=3,  # Default aus settings.py
            ai_limit_live_guidance=50,  # Default aus settings.py
            ai_limit_analysis=10,  # Default aus settings.py
        )
        print("[OK] Initial SiteSettings created with defaults")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_sitesettings_userprofile_custom_ai_limit_analysis_and_more"),
    ]

    operations = [
        migrations.RunPython(create_initial_site_settings, migrations.RunPython.noop),
    ]
