# Generated by Django 5.2.11 on 2026-02-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_create_initial_site_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="has_seen_onboarding",
            field=models.BooleanField(
                default=False,
                help_text="True = User hat die Onboarding-Tour abgeschlossen",
                verbose_name="Onboarding gesehen",
            ),
        ),
    ]
