# Generated by Django 5.2.11 on 2026-03-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_userprofile_has_seen_onboarding"),
    ]

    operations = [
        migrations.AddField(
            model_name="koerperwerte",
            name="grundumsatz_kcal",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Basaler Energieumsatz (BMR) in kcal",
                null=True,
                verbose_name="Grundumsatz (kcal)",
            ),
        ),
        migrations.AddField(
            model_name="koerperwerte",
            name="koerperwasser_prozent",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True, verbose_name="Wasser (%)"
            ),
        ),
        migrations.AddField(
            model_name="koerperwerte",
            name="viszeralfett",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Viszeralfett-Stufe (1-59), je nach Waage",
                null=True,
                verbose_name="Viszeralfett (Stufe)",
            ),
        ),
    ]
