# Generated by Django 5.2.12 on 2026-03-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_add_body_stats_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="satz",
            name="is_pr",
            field=models.BooleanField(
                default=False,
                help_text="Dieser Satz ist ein neuer persönlicher Rekord",
                verbose_name="Persönlicher Rekord",
            ),
        ),
        migrations.AddField(
            model_name="satz",
            name="pr_previous_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="1RM-Wert vor diesem PR",
                max_digits=8,
                null=True,
                verbose_name="Vorheriger Rekordwert",
            ),
        ),
        migrations.AddField(
            model_name="satz",
            name="pr_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("best_1rm", "Bestes 1RM"),
                    ("max_weight", "Neues Max-Gewicht"),
                    ("max_reps", "Neue Wdh auf gleichem Gewicht"),
                    ("first", "Erster Satz dieser Übung"),
                ],
                max_length=20,
                null=True,
                verbose_name="PR-Typ",
            ),
        ),
    ]
