# Generated by Django 6.0.3 on 2026-03-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0078_add_trainingsblock_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="planuebung",
            name="rpe_ziel",
            field=models.FloatField(
                blank=True,
                help_text="Ziel-RPE für diese Übung (z.B. 8.0). Steuert Gewichtssteigerung.",
                null=True,
                verbose_name="Ziel-RPE",
            ),
        ),
    ]
