# Generated by Django 5.2.11 on 2026-03-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_add_rpe_ziel_to_planuebung"),
    ]

    operations = [
        migrations.AddField(
            model_name="uebung",
            name="gewichts_richtung",
            field=models.CharField(
                choices=[
                    ("ZUSATZ", "Zusatzgewicht (wird addiert)"),
                    ("GEGEN", "Gegengewicht (wird subtrahiert, z.B. assistierte Dips)"),
                ],
                default="ZUSATZ",
                help_text="ZUSATZ: Gewicht wird zum Körpergewicht addiert (normale Dips/Klimmzüge). GEGEN: Gewicht wird subtrahiert (assistierte Dips/Klimmzüge am Gerät).",
                max_length=10,
                verbose_name="Gewichtsrichtung",
            ),
        ),
    ]
