# Generated by Django 5.2.11 on 2026-04-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0081_add_assisted_exercises"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingsblock",
            name="plan_dauer_wochen",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Geplante Dauer (Wochen)"
            ),
        ),
    ]
