# Generated by Django 5.2.11 on 2026-04-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0082_add_plan_dauer_wochen_to_trainingsblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingsblock",
            name="schwachstellen_snapshot",
            field=models.JSONField(
                blank=True,
                help_text="JSON-Liste von {muskelgruppe, ist_saetze, soll_min, soll_max} zum Zeitpunkt der Plananalyse",
                null=True,
                verbose_name="Schwachstellen-Snapshot",
            ),
        ),
    ]
