# Generated by Django 5.2.11 on 2026-06-02 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0083_add_schwachstellen_snapshot_to_trainingsblock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingsPause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_datum", models.DateField(verbose_name="Startdatum")),
                (
                    "end_datum",
                    models.DateField(
                        blank=True,
                        help_text="Leer lassen für eine noch laufende Pause.",
                        null=True,
                        verbose_name="Enddatum",
                    ),
                ),
                (
                    "grund",
                    models.CharField(
                        choices=[
                            ("krankheit", "Krankheit"),
                            ("verletzung", "Verletzung"),
                            ("urlaub", "Urlaub"),
                            ("sonstiges", "Sonstiges"),
                        ],
                        default="sonstiges",
                        max_length=20,
                        verbose_name="Grund",
                    ),
                ),
                ("notiz", models.TextField(blank=True, verbose_name="Notiz")),
                ("erstellt_am", models.DateTimeField(auto_now_add=True)),
                ("geaendert_am", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainingspausen",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trainingspause",
                "verbose_name_plural": "Trainingspausen",
                "ordering": ["-start_datum"],
                "indexes": [
                    models.Index(fields=["user", "start_datum"], name="pause_user_start_idx"),
                    models.Index(fields=["user", "end_datum"], name="pause_user_end_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_datum__isnull", True),
                            ("end_datum__gte", models.F("start_datum")),
                            _connector="OR",
                        ),
                        name="trainingspause_end_nach_start",
                    )
                ],
            },
        ),
    ]
