# Generated by Django 5.2.11 on 2026-07-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0084_add_trainingspause"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingspause",
            name="aerztliche_freigabe_noetig",
            field=models.BooleanField(
                default=False,
                help_text="Bei medizinischen Pausen (z.B. nach OP): Der Wiedereinstieg berücksichtigt dies konservativer und weist auf die nötige ärztliche Freigabe hin.",
                verbose_name="Ärztliche Freigabe nötig",
            ),
        ),
    ]
